# Generated by Django 4.1 on 2024-05-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0002_alter_shipping_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipping",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("processing", "Processing"),
                    ("on_the_way", "On The Way"),
                    ("arrived", "Arrived"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
