# Generated by Django 4.1 on 2024-05-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0003_alter_shipping_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipping",
            name="tracking",
            field=models.JSONField(blank=True, max_length=600, null=True),
        ),
    ]
