# Generated by Django 4.1 on 2024-05-14 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0044_alter_product_carbon_footprint_co2"),
        ("admin_panel", "0004_shipping_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonOffset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offSet_price", models.FloatField(blank=True, null=True)),
                (
                    "offSet_status",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "certificate",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process_occ.order",
                    ),
                ),
            ],
        ),
    ]
