# Generated by Django 4.1 on 2024-05-15 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0044_alter_product_carbon_footprint_co2"),
        ("admin_panel", "0005_carbonoffset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carbonoffset",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process_occ.order",
            ),
        ),
    ]
