# Generated by Django 4.2.3 on 2024-04-29 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coatings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="HeatTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Inspections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("United Kingdom", "United Kingdom"),
                            ("EUROPEAN", "EUROPEAN"),
                            ("Rest", "Rest"),
                        ],
                        default="Rest",
                        max_length=25,
                    ),
                ),
                ("express_price", models.FloatField()),
                ("fast_price", models.FloatField()),
                ("normal_price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="stp_file/")),
                ("name", models.CharField(max_length=100)),
                ("raw_area", models.FloatField(blank=True, null=True)),
                ("raw_volume", models.FloatField(blank=True, null=True)),
                ("raw_length", models.FloatField(blank=True, null=True)),
                ("raw_width", models.FloatField(blank=True, null=True)),
                ("raw_height", models.FloatField(blank=True, null=True)),
                ("volume_mm3", models.FloatField(blank=True, null=True)),
                ("area_mm2", models.FloatField(blank=True, null=True)),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("extended_length", models.FloatField(blank=True, null=True)),
                ("extended_width", models.FloatField(blank=True, null=True)),
                ("extended_height", models.FloatField(blank=True, null=True)),
                ("finished_weight", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_confirm", models.DateTimeField(blank=True, null=True)),
                ("material_cutting", models.DateTimeField(blank=True, null=True)),
                ("machining", models.DateTimeField(blank=True, null=True)),
                ("inspection", models.DateTimeField(blank=True, null=True)),
                ("shipping", models.DateTimeField(blank=True, null=True)),
                ("order_delivery", models.DateTimeField(blank=True, null=True)),
                ("carbon_footprint", models.FloatField(blank=True, null=True)),
                ("delivery_charges", models.FloatField(blank=True, null=True)),
                ("tax", models.FloatField(blank=True, null=True)),
                ("order_total", models.FloatField(blank=True, null=True)),
                (
                    "accept_offset_terms_and_conditions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "accept_manufaturing_terms_and_conditions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("material_cutting", "Material Cutting"),
                            ("machining", "Machining"),
                            ("inspection", "Inspection"),
                            ("shipping", "Shipping"),
                            ("order_delivery", "Order Delivery"),
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("is_delivered", models.BooleanField(default=False)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("expected_delivered", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="orders", to="process_occ.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("price", models.FloatField(blank=True, null=True)),
                ("is_material_category", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "parent_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="process_occ.material",
                    ),
                ),
            ],
        ),
    ]
