# Generated by Django 4.2.3 on 2024-05-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="extended_height",
            new_name="final_area_mm2",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="extended_length",
            new_name="final_finished_weight",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="extended_width",
            new_name="final_height",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="raw_area",
            new_name="final_length",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="raw_height",
            new_name="final_volume_mm3",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="raw_length",
            new_name="final_width",
        ),
        migrations.RemoveField(
            model_name="product",
            name="raw_volume",
        ),
        migrations.RemoveField(
            model_name="product",
            name="raw_width",
        ),
        migrations.AlterField(
            model_name="product",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
