# Generated by Django 4.1 on 2024-05-01 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0002_rename_extended_height_product_final_area_mm2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="density",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="Material_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="process_occ.material",
            ),
        ),
    ]
