# Generated by Django 4.1 on 2024-05-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0004_rename_material_id_product_material_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryCO2Intensity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=40)),
                ("value", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="material",
            name="mm2_coeff_cn_finished",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="mm2_coeff_eu_finished",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="mm2_coeff_uk_finished",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="mm3_coeff_cn_removed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="mm3_coeff_eu_removed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="mm3_coeff_uk_removed",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
