# Generated by Django 4.1 on 2024-05-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "process_occ",
            "0005_countryco2intensity_material_mm2_coeff_cn_finished_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="material",
            old_name="mm2_coeff_cn_finished",
            new_name="mm2_coeff_cn_finished_price",
        ),
        migrations.RenameField(
            model_name="material",
            old_name="mm2_coeff_eu_finished",
            new_name="mm2_coeff_eu_finished_price",
        ),
        migrations.RenameField(
            model_name="material",
            old_name="mm2_coeff_uk_finished",
            new_name="mm2_coeff_uk_finished_price",
        ),
        migrations.RenameField(
            model_name="material",
            old_name="mm3_coeff_cn_removed",
            new_name="mm3_coeff_cn_removed_price",
        ),
        migrations.RenameField(
            model_name="material",
            old_name="mm3_coeff_eu_removed",
            new_name="mm3_coeff_eu_removed_price",
        ),
        migrations.RenameField(
            model_name="material",
            old_name="mm3_coeff_uk_removed",
            new_name="mm3_coeff_uk_removed_price",
        ),
        migrations.AddField(
            model_name="coatings",
            name="cost_cn_per_mm2",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="coatings",
            name="cost_eu_per_mm2",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="coatings",
            name="cost_uk_per_mm2",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="heattreatment",
            name="cost_cn_per_kg",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="heattreatment",
            name="cost_eu_per_kg",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="heattreatment",
            name="cost_uk_per_kg",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="inspections",
            name="cost_cn_per_mm2",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="inspections",
            name="cost_eu_per_mm2",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="inspections",
            name="cost_uk_per_mm2",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="material",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
