# Generated by Django 4.1 on 2024-05-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0010_kgco2epertxkm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kgco2epertxkm",
            name="transport_mode",
        ),
        migrations.DeleteModel(
            name="PackagingMaterial",
        ),
        migrations.RemoveField(
            model_name="transport",
            name="country",
        ),
        migrations.RemoveField(
            model_name="transport",
            name="transport_mode",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="final_finished_weight",
            new_name="over_height_mm",
        ),
        migrations.AddField(
            model_name="product",
            name="over_length_mm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="over_width_mm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="KgCo2ePerTxKm",
        ),
        migrations.DeleteModel(
            name="Transport",
        ),
        migrations.DeleteModel(
            name="TransportMode",
        ),
    ]
