# Generated by Django 4.1 on 2024-05-04 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0017_packagingmaterial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TransportSpeed",
            new_name="TransportType",
        ),
    ]
