# Generated by Django 4.1 on 2024-05-04 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0018_rename_transportspeed_transporttype"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TransportMode",
            new_name="TransportVehicle",
        ),
    ]
