# Generated by Django 4.1 on 2024-05-04 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0019_rename_transportmode_transportvehicle"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TransportCOst",
            new_name="TransportCostPerKg",
        ),
    ]
