# Generated by Django 4.1 on 2024-05-04 22:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0020_rename_transportcost_transportcostperkg"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="KgCo2ePerTxKm",
            new_name="KgCo2ePerTonKm",
        ),
    ]
