# Generated by Django 4.1 on 2024-05-07 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "process_occ",
            "0022_order_kg_co2e_packaging_order_total_packaging_weight_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name="transportcostperkg",
            old_name="transport_speed",
            new_name="transport_type",
        ),
        migrations.RenameField(
            model_name="transporttype",
            old_name="transport_speed",
            new_name="transport_type",
        ),
        migrations.RemoveField(
            model_name="material",
            name="is_material_category",
        ),
        migrations.RemoveField(
            model_name="transport",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="transport",
            name="speed",
        ),
        migrations.RemoveField(
            model_name="transport",
            name="transport_mode",
        ),
        migrations.AddField(
            model_name="product",
            name="surface_area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transport",
            name="cost_transport",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transport",
            name="kgCO2e_packaging",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transport",
            name="kgCO2e_transport",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transport",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process_occ.order",
            ),
        ),
        migrations.AddField(
            model_name="transport",
            name="transport_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="select_transport_type",
                to="process_occ.transporttype",
            ),
        ),
        migrations.AddField(
            model_name="transport",
            name="transport_vehicle_one",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="select_transport_vehicle_one",
                to="process_occ.transportvehicle",
            ),
        ),
        migrations.AddField(
            model_name="transport",
            name="transport_vehicle_one_cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transport",
            name="transport_vehicle_two",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="select_transport_vehicle_two",
                to="process_occ.transportvehicle",
            ),
        ),
        migrations.AddField(
            model_name="transport",
            name="transport_vehicle_two_cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transportvehicle",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="parent_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process_occ.parentmaterial",
            ),
        ),
    ]
