# Generated by Django 4.1 on 2024-05-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0024_remove_manufacturer_name_manufacturer_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturerCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="express_price",
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="fast_price",
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="normal_price",
        ),
    ]
