# Generated by Django 4.1 on 2024-05-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "process_occ",
            "0025_manufacturercost_remove_manufacturer_express_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process_occ.manufacturercost",
            ),
        ),
    ]
