# Generated by Django 4.1 on 2024-05-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0026_manufacturer_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufacturer",
            name="price",
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="price",
            field=models.ManyToManyField(to="process_occ.manufacturercost"),
        ),
    ]
