# Generated by Django 4.1 on 2024-05-07 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0027_remove_manufacturer_price_manufacturer_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufacturer_cost",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process_occ.manufacturercost",
            ),
        ),
    ]
