# Generated by Django 4.1 on 2024-05-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0028_product_manufacturer_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="billet_mm3",
        ),
        migrations.AddField(
            model_name="product",
            name="over_length_in_mm",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
