# Generated by Django 4.1 on 2024-05-08 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0029_remove_product_billet_mm3_product_over_length_in_mm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="finished_mm2",
        ),
        migrations.RemoveField(
            model_name="product",
            name="finished_mm3",
        ),
    ]
