# Generated by Django 4.1 on 2024-05-08 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0030_remove_product_finished_mm2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="country_CO2_intensity",
        ),
    ]
