# Generated by Django 4.1 on 2024-05-09 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0032_product_carbon_footprint_co2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tolerance",
            name="material",
        ),
        migrations.AddField(
            model_name="product",
            name="co2_intensity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process_occ.countryco2intensity",
            ),
        ),
        migrations.AddField(
            model_name="tolerance",
            name="tolerancing",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
