# Generated by Django 4.1 on 2024-05-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0034_shippingto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingto",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="shippingto",
            name="zip_postal_pinconde",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
