# Generated by Django 4.1 on 2024-05-09 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("process_occ", "0035_alter_shippingto_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingto",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
