# Generated by Django 4.1 on 2024-05-12 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("process_occ", "0036_shippingto_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturerLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "duration",
                    models.CharField(
                        choices=[("Days", "Days"), ("Weeks", "Weeks")],
                        default="Weeks",
                        max_length=25,
                    ),
                ),
                ("min_time", models.PositiveIntegerField()),
                ("max_time", models.PositiveIntegerField()),
                ("price", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "quote_id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
                (
                    "total_parts",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "total_quantity",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("lead_time", models.DateTimeField(blank=True, null=True)),
                (
                    "carbon_footprint",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "cost_to_carbon",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("order_total", models.FloatField(blank=True, default=0, null=True)),
                (
                    "order_sub_total",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("approved", models.BooleanField(default=False)),
                (
                    "manufacturing_terms_and_conditions",
                    models.BooleanField(default=False),
                ),
                (
                    "carbon_offsetting_terms_and_conditions",
                    models.BooleanField(default=False),
                ),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TermsAndConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accept_offset_terms_and_conditions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "accept_manufaturing_terms_and_conditions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="order",
            old_name="expected_delivered",
            new_name="promise_date",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="inspection",
            new_name="supplier_due_date",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="customer",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="price",
        ),
        migrations.RemoveField(
            model_name="order",
            name="accept_manufaturing_terms_and_conditions",
        ),
        migrations.RemoveField(
            model_name="order",
            name="accept_offset_terms_and_conditions",
        ),
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_charges",
        ),
        migrations.RemoveField(
            model_name="order",
            name="kg_CO2e_packaging",
        ),
        migrations.RemoveField(
            model_name="order",
            name="machining",
        ),
        migrations.RemoveField(
            model_name="order",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="material_cutting",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_confirm",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_delivery",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_total",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping",
        ),
        migrations.RemoveField(
            model_name="order",
            name="tax",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_packaging_weight",
        ),
        migrations.RemoveField(
            model_name="product",
            name="manufacturer_cost",
        ),
        migrations.AddField(
            model_name="order",
            name="buyer_initials",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process_occ.country",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="added_in_basket",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.RenameModel(
            old_name="ShippingTo",
            new_name="ShippingAddress",
        ),
        migrations.DeleteModel(
            name="ManufacturerCost",
        ),
        migrations.AddField(
            model_name="quote",
            name="manufacturing_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="process_occ.country",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="products",
            field=models.ManyToManyField(to="process_occ.product"),
        ),
        migrations.AddField(
            model_name="quote",
            name="shipping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process_occ.shippingaddress",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="lead_time",
            field=models.ManyToManyField(to="process_occ.manufacturerlead"),
        ),
        migrations.AddField(
            model_name="order",
            name="manufacturer_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process_occ.manufacturerlead",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process_occ.manufacturerlead",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orders", to="process_occ.product"
            ),
        ),
    ]
