# Generated by Django 4.1 on 2024-05-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0040_alter_manufacturer_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="material_removed_price_per_100_mm3",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="price_per_1000000_mm3",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
