# Generated by Django 4.1 on 2024-05-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0041_material_material_removed_price_per_100_mm3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="delivery_charges",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="tax",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
