# Generated by Django 4.1 on 2024-05-15 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0044_alter_product_carbon_footprint_co2"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="order_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="process_occ.order",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="carbon_footprint_CO2",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
