# Generated by Django 4.1 on 2024-05-20 02:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0047_alter_coatings_country_alter_heattreatment_country"),
        ("process_occ", "0047_alter_heattreatment_country"),
    ]

    operations = []
