# Generated by Django 4.1 on 2024-05-20 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0048_merge_20240520_0740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heattreatment",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="process_occ.country"
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="quote_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
