# Generated by Django 4.1 on 2024-05-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process_occ", "0049_alter_heattreatment_country_alter_quote_quote_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="cost",
            field=models.FloatField(default=0),
        ),
    ]
